import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Footer from "./Footer/Footer";
import Header from "./Header/page";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MediaCraft Creative Studio",
  description: "Generated by next",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} min-h-full flex flex-col mx-auto`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
